# Dockerfile for setting up a local development environment. Note that this
# should not be used for production.
version: "3"
services:
  parity:
    container_name: "parity"
    image: parity/parity:v2.4.5
    # Parity by default only exposes it's API on localhost. For it to be
    # accessible from the other containers we need --unsafe-expose
    command: ['--chain', 'dev', '--unsafe-expose']
    ports:
      - '8545:8545'
